apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
      tier: database
  template:
    metadata:
      labels:
        app: mariadb
        tier: database
    spec:
      containers:
      - name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadbpassword
              key: password
        image: mariadb
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadbvolume
          mountPath: /var/lib/mysql
      volumes:
       - name: mariadbvolume
         persistentVolumeClaim:
           claimName: mariadbvolume